project:
  type: website
  output-dir: docs


website:
  title: "Yiqing Yuan"
  navbar:
    left:
      - text: Home
        href: index.qmd#top
      - text: Research
        href: index.qmd#research
      - text: CV
        href: index.qmd#cv
      - text: Blog
        href: blog/
      - text: Contact
        href: index.qmd#contact

format:
  html:
    theme:
      - flatly
      - styles.scss
    toc: false
    smooth-scroll: true
    grid:
      body-width: 1400px
      margin-width: 0px
      gutter-width: 2rem
